const data = [
  {
    skill: "Product Thinking",
    value: 9,
    projects: [
      {
        name: "E-commerce Redesign",
        link: "/projects/ecommerce-redesign",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Redesign of an e-commerce platform to improve user experience and conversion rates.",
        published: "2023-01-15",
        lastUpdated: "2023-06-10",
        createdBy: "Jane Doe",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Alice Brown",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["UX", "E-commerce", "Redesign"],
      },
      {
        name: "FinTech App",
        link: "/projects/fintech-app",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Development of a financial technology app for personal finance management.",
        published: "2022-11-22",
        lastUpdated: "2023-05-08",
        createdBy: "John Smith",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Emily White",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Finance", "App", "Development"],
      },
    ],
  },
  {
    skill: "Coding",
    value: 7,
    projects: [
      {
        name: "Portfolio Website",
        link: "/projects/portfolio-website",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "A personal portfolio website showcasing various projects and skills.",
        published: "2021-09-10",
        lastUpdated: "2022-03-14",
        createdBy: "Alice Johnson",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Michael Lee",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Web Development", "Portfolio"],
      },
      {
        name: "Interactive Dashboard",
        link: "/projects/interactive-dashboard",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "An interactive data visualization dashboard for business analytics.",
        published: "2022-06-05",
        lastUpdated: "2022-12-01",
        createdBy: "Michael Lee",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Sarah Wilson",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Dashboard", "Data Visualization", "Analytics"],
      },
    ],
  },
  {
    skill: "Interaction Design",
    value: 9,
    projects: [
      {
        name: "Mobile Game UI",
        link: "/projects/mobile-game-ui",
        thumbnail: "https://via.placeholder.com/150",
        description: "User interface design for a mobile game application.",
        published: "2023-02-28",
        lastUpdated: "2023-04-20",
        createdBy: "Sarah Wilson",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Daniel Brown",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["UI Design", "Mobile", "Game"],
      },
      {
        name: "Smart Home App",
        link: "/projects/smart-home-app",
        thumbnail: "https://via.placeholder.com/150",
        description: "Design of a smart home control application.",
        published: "2021-12-15",
        lastUpdated: "2022-07-18",
        createdBy: "Daniel Brown",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Emily White",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Smart Home", "App", "UI Design"],
      },
    ],
  },
  {
    skill: "Critical Thinking",
    value: 8,
    projects: [
      {
        name: "UX Case Study",
        link: "/projects/ux-case-study",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "A detailed case study on user experience design for a mobile app.",
        published: "2023-03-05",
        lastUpdated: "2023-05-10",
        createdBy: "Emily Davis",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Kevin Martin",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["UX", "Case Study", "Mobile"],
      },
      {
        name: "Product Strategy Document",
        link: "/projects/product-strategy",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Comprehensive product strategy document for a new software product.",
        published: "2022-05-20",
        lastUpdated: "2022-11-30",
        createdBy: "Kevin Martin",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Olivia Taylor",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Product Strategy", "Documentation"],
      },
    ],
  },
  {
    skill: "System Thinking",
    value: 8,
    projects: [
      {
        name: "Design System",
        link: "/projects/design-system",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Creation of a scalable design system for a large organization.",
        published: "2021-11-10",
        lastUpdated: "2022-06-15",
        createdBy: "Olivia Taylor",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "James White",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Design System", "Scalability"],
      },
      {
        name: "Enterprise Software Architecture",
        link: "/projects/enterprise-software",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Architectural design for enterprise-level software solutions.",
        published: "2020-08-25",
        lastUpdated: "2021-03-01",
        createdBy: "James White",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Sophia Thomas",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Enterprise Software", "Architecture"],
      },
    ],
  },
  {
    skill: "Tools Proficiency",
    value: 9,
    projects: [
      {
        name: "Figma Prototype",
        link: "/projects/figma-prototype",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "A high-fidelity prototype created in Figma for a mobile app.",
        published: "2022-02-10",
        lastUpdated: "2022-09-20",
        createdBy: "Sophia Thomas",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Liam Roberts",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Figma", "Prototype", "Mobile"],
      },
      {
        name: "Adobe Creative Suite Project",
        link: "/projects/adobe-project",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Various design projects using Adobe Creative Suite tools.",
        published: "2021-04-18",
        lastUpdated: "2021-12-05",
        createdBy: "Liam Roberts",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Olivia Taylor",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Adobe", "Creative Suite", "Design"],
      },
    ],
  },
  {
    skill: "User Research",
    value: 8,
    projects: [
      {
        name: "User Persona Development",
        link: "/projects/user-personas",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Development of detailed user personas for a target audience.",
        published: "2022-01-25",
        lastUpdated: "2022-08-30",
        createdBy: "Isabella Walker",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Ethan Harris",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["User Research", "Personas"],
      },
      {
        name: "Usability Testing Report",
        link: "/projects/usability-testing",
        thumbnail: "https://via.placeholder.com/150",
        description:
          "Comprehensive report on usability testing for a web application.",
        published: "2021-06-14",
        lastUpdated: "2022-01-22",
        createdBy: "Ethan Harris",
        createdByAvatar: "https://via.placeholder.com/24",
        reviewedBy: "Emily White",
        reviewedByAvatar: "https://via.placeholder.com/24",
        tags: ["Usability Testing", "Web", "Research"],
      },
    ],
  },
];

export default data;
